package mensaje;

public enum TipoMensaje {
    CERRAR_CONEXION,
    CERRAR_CONEXION_OK,
    CONEXION_CLIENTE,
    CONEXION_ERROR,
    CONEXION_OK,
    EMISOR_LISTO,
    ELIMINAR_FICHERO,
    ELIMINAR_FICHERO_OK,
    AVISO_EMISOR,
    AVISO_RECEPTOR,
    LISTA_USUARIOS,
    LISTA_USUARIOS_OK,
    NUEVO_FICHERO,
    NUEVO_FICHERO_OK,
    NUEVO_FICHERO_ERROR,
    PEDIR_FICHERO,
    PEDIR_FICHERO_ERROR,
    CERRAR_CONEXION_ERROR,
    DESCARGA_EXITO
}

